/**
 * Legacy Code Cartographer — Characterization Test Synthesizer
 *
 * Generates black-box characterization tests for undocumented, untested modules.
 * Tests cover: edge inputs, type boundaries, exception states.
 */

import * as fs from 'node:fs/promises';
import * as path from 'node:path';

export interface CharacterizationTest {
  testName: string;
  targetFunction: string;
  inputDescription: string;
  expectedBehavior: string;
  testCode: string;
}

export interface SynthesisResult {
  filePath: string;
  generatedTests: CharacterizationTest[];
  testFilePath: string;
}

/**
 * Synthesizes characterization tests for a given source file.
 * Production implementation would use ts-morph for proper AST analysis.
 *
 * @param filePath - Absolute path to the legacy module
 * @param outputDir - Directory to write generated test files
 */
export async function synthesizeTests(
  filePath: string,
  outputDir: string
): Promise<SynthesisResult> {
  const content = await fs.readFile(filePath, 'utf8');
  const basename = path.basename(filePath, path.extname(filePath));

  // Extract exported function names via simple regex
  // TODO: Replace with ts-morph AST traversal for production
  const exportedFunctions: string[] = [];
  const exportMatches = content.matchAll(/export\s+(?:async\s+)?function\s+(\w+)/g);
  for (const match of exportMatches) {
    exportedFunctions.push(match[1]);
  }

  const tests: CharacterizationTest[] = exportedFunctions.map((fnName) => ({
    testName: `characterize_${fnName}`,
    targetFunction: fnName,
    inputDescription: 'Auto-generated edge case and boundary inputs',
    expectedBehavior: 'Recorded from actual execution (golden master)',
    testCode: generateTestCode(fnName, basename),
  }));

  const testContent = buildTestFile(basename, filePath, tests);
  const testFilePath = path.join(outputDir, `${basename}.characterization.test.ts`);
  await fs.mkdir(outputDir, { recursive: true });
  await fs.writeFile(testFilePath, testContent, 'utf8');

  return { filePath, generatedTests: tests, testFilePath };
}

function generateTestCode(fnName: string, moduleName: string): string {
  return `
  it('characterizes ${fnName} with null input', async () => {
    // TODO: Record actual output and pin as golden master
    const result = await ${fnName}(null as any);
    expect(result).toMatchSnapshot();
  });

  it('characterizes ${fnName} with empty object', async () => {
    const result = await ${fnName}({} as any);
    expect(result).toMatchSnapshot();
  });

  it('characterizes ${fnName} with boundary values', async () => {
    const result = await ${fnName}({ value: Number.MAX_SAFE_INTEGER } as any);
    expect(result).toMatchSnapshot();
  });
  `.trim();
}

function buildTestFile(moduleName: string, filePath: string, tests: CharacterizationTest[]): string {
  return `/**
 * Characterization Tests for: ${moduleName}
 * Auto-generated by AgentUtils Legacy Code Cartographer
 * Source: ${filePath}
 *
 * WARNING: These tests record CURRENT behavior, not intended behavior.
 * Do NOT modify these tests before reviewing the behavior contract.
 */

import { describe, it, expect } from 'vitest';
// TODO: Update import path after reviewing module exports
// import * as ${moduleName} from '${filePath}';

describe('${moduleName} — Characterization Tests', () => {
${tests.map((t) => t.testCode).join('\n\n')}
});
`;
}
